server:
  port: 8888

spring:
  application:
    name: gateway-application
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        - id: csdn1 # 路由的编号
          uri: http://localhost:9090
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/csdnblog/**
          filters:
            - StripPrefix=1
# 记录网关日志
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG