server:
  port: 9090

spring:
  application:
    name: gateway-controller-application
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

# 记录网关日志
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
    cn.iocoder.springcloud.labx08.gatewaydemo: debug